### ISSUE TITLE
Not working on Incognito Properly

### ISSUE THREAD

**Issue by iamonlysaiful** [patriziofilloramo/ngx-msal#22]
After login, It reloads again and again...
How to stop can't understand.

Here is my configuration 

```
export const msalConfig: MsalConfiguration = {
  auth: {
    clientId: environment.clientId,
    authority: environment.authority,
    validateAuthority: true,
    redirectUri: environment.redirectUrl,
    postLogoutRedirectUri: environment.postLogoutRedirectUri,
    navigateToLoginRequestUrl: false,
  },
  framework: {
    popUp: false,
    protectedResourceMap: [['https://graph.microsoft.com', ['User.Read']], ['https://management.azure.com/.default']],
    unprotectedResources: ['https://www.microsoft.com/en-us/'],
    consentScopes: ['User.Read', 'openid'],
  },
};
```

**Comment by patriziofilloramo** [comment]
One reason might be that the token negotiation failed.

Please check your console log error message, they can give us some hints why it happens.
_For debugging reason only make sure you preserve the logs when reloading:_
![image](https://user-images.githubusercontent.com/20513856/152117094-612c45f7-d714-4d81-a5b3-ef7dacdfe421.png)

Without more information, I assume that a configuration in the azure portal might be missing or wrong.
Make sure the redirect url is present under your app registration -> authentication -> Single Page Applications -> redirect urls
more info here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-spa-app (step 2.3)

**Comment by iamonlysaiful** [comment]
Hey @patriziofilloramo my all configuration is ok and working fine on Chrome on normal window perfectly.

Not working on **Incognito mode** 

Here is my console.

![image](https://user-images.githubusercontent.com/25750962/152124347-89719d15-87d0-404d-9309-9aaae5786161.png)
